2022-02-19 06:43:09,846 INFO    MainThread:560 [wandb_setup.py:_flush():69] setting env: {}
2022-02-19 06:43:09,846 INFO    MainThread:560 [wandb_setup.py:_flush():69] setting login settings: {}
2022-02-19 06:43:09,847 INFO    MainThread:560 [wandb_init.py:_log_setup():336] Logging user logs to /workspace/graph-neural-pde/src/wandb/run-20220219_064309-1qxcih4w/logs/debug.log
2022-02-19 06:43:09,847 INFO    MainThread:560 [wandb_init.py:_log_setup():337] Logging internal logs to /workspace/graph-neural-pde/src/wandb/run-20220219_064309-1qxcih4w/logs/debug-internal.log
2022-02-19 06:43:09,847 INFO    MainThread:560 [wandb_init.py:init():369] calling init triggers
2022-02-19 06:43:09,847 INFO    MainThread:560 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2022-02-19 06:43:09,848 INFO    MainThread:560 [wandb_init.py:init():418] starting backend
2022-02-19 06:43:09,848 INFO    MainThread:560 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-19 06:43:09,890 INFO    MainThread:560 [backend.py:ensure_launched():123] starting backend process...
2022-02-19 06:43:09,917 INFO    MainThread:560 [backend.py:ensure_launched():128] started backend process with pid: 610
2022-02-19 06:43:09,920 INFO    MainThread:560 [wandb_init.py:init():423] backend started and connected
2022-02-19 06:43:09,921 INFO    MainThread:560 [wandb_init.py:init():465] updated telemetry
2022-02-19 06:43:09,922 INFO    MainThread:560 [wandb_init.py:init():484] communicating current version
2022-02-19 06:43:10,609 INFO    MainThread:560 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-19 06:43:10,610 INFO    MainThread:560 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-02-19 06:43:11,120 INFO    MainThread:560 [wandb_init.py:init():522] starting run threads in backend
2022-02-19 06:43:13,665 WARNING MainThread:560 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 525, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 783, in communicate_run_start
    result = self._communicate(rec)
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 533, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/opt/conda/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
