2022-02-15 13:54:24,639 INFO    MainThread:199227 [wandb_setup.py:_flush():69] setting env: {}
2022-02-15 13:54:24,639 INFO    MainThread:199227 [wandb_setup.py:_flush():69] setting login settings: {}
2022-02-15 13:54:24,640 INFO    MainThread:199227 [wandb_init.py:_log_setup():336] Logging user logs to /workspace/graph-neural-pde/src/wandb/run-20220215_135424-test_run_log_nfe/logs/debug.log
2022-02-15 13:54:24,640 INFO    MainThread:199227 [wandb_init.py:_log_setup():337] Logging internal logs to /workspace/graph-neural-pde/src/wandb/run-20220215_135424-test_run_log_nfe/logs/debug-internal.log
2022-02-15 13:54:24,640 INFO    MainThread:199227 [wandb_init.py:init():369] calling init triggers
2022-02-15 13:54:24,641 INFO    MainThread:199227 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2022-02-15 13:54:24,641 INFO    MainThread:199227 [wandb_init.py:init():418] starting backend
2022-02-15 13:54:24,641 INFO    MainThread:199227 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-15 13:54:24,688 INFO    MainThread:199227 [backend.py:ensure_launched():123] starting backend process...
2022-02-15 13:54:24,698 INFO    MainThread:199227 [backend.py:ensure_launched():128] started backend process with pid: 199277
2022-02-15 13:54:24,699 INFO    MainThread:199227 [wandb_init.py:init():423] backend started and connected
2022-02-15 13:54:24,700 INFO    MainThread:199227 [wandb_init.py:init():465] updated telemetry
2022-02-15 13:54:24,700 INFO    MainThread:199227 [wandb_init.py:init():484] communicating current version
2022-02-15 13:54:25,426 INFO    MainThread:199227 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-15 13:54:25,427 INFO    MainThread:199227 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-02-15 13:54:32,672 WARNING MainThread:199227 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 498, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 652, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 640, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 533, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/opt/conda/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
